name: Build, Test & Analyze with SonarCloud

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    name: Build and Analyze
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Install Coverlet globally
        run: dotnet tool install --global coverlet.console

      - name: Add tools to PATH
        run: echo "$HOME/.dotnet/tools" >> $GITHUB_PATH

      - name: Restore dependencies
        run: dotnet restore InvoiceManager/InvoiceManager.sln

      - name: Begin SonarCloud analysis
        run: |
          dotnet sonarscanner begin \
            /k:"murgocimark_net.core" \
            /o:"murgocimark" \
            /d:sonar.login="${{ secrets.SONAR_TOKEN }}" \
            /d:sonar.host.url="https://sonarcloud.io" \
            /d:sonar.cs.opencover.reportsPaths="coverage/coverage.opencover.xml" \
            /d:sonar.cs.vstest.reportsPaths="**/TestResults/*.trx"

      - name: Build solution
        run: dotnet build InvoiceManager/InvoiceManager.sln --no-restore

      - name: Run tests (no coverage, just TRX logs)
        run: dotnet test InvoiceManager/InvoiceManager.sln --no-build --logger:trx

      - name: Run Coverlet to collect OpenCover coverage
        run: |
          coverlet ./InvoiceManager/tests/Invoice.Tests/bin/Debug/net8.0/Invoice.Tests.dll \
            --target "dotnet" \
            --targetargs "test InvoiceManager/InvoiceManager.sln --no-build" \
            --format opencover \
            --output coverage/coverage.opencover.xml

      - name: End SonarCloud analysis
        run: dotnet sonarscanner end /d:sonar.login="${{ secrets.SONAR_TOKEN }}"
