name: Build and analyze

on:
  push:
    branches: [ main ]

jobs:
  build:
    name: Build and SonarCloud Analysis
    runs-on: ubuntu-latest

    env:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Install SonarScanner
        run: dotnet tool install --global dotnet-sonarscanner

      - name: Begin SonarCloud analysis
        run: dotnet sonarscanner begin /k:"your_project_key" /o:"your_org" /d:sonar.host.url="https://sonarcloud.io" /d:sonar.login="${{ secrets.SONAR_TOKEN }}"
        working-directory: InvoiceManager

      - name: Build
        run: dotnet build --no-restore
        working-directory: InvoiceManager

      - name: Run tests
        run: dotnet test --no-build --logger:trx
        working-directory: InvoiceManager

      - name: End SonarCloud analysis
        run: dotnet sonarscanner end /d:sonar.login="${{ secrets.SONAR_TOKEN }}"
        working-directory: InvoiceManager
