name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest

    env:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Install SonarScanner
        run: dotnet tool install --global dotnet-sonarscanner

      - name: Begin SonarCloud analysis
        run: dotnet sonarscanner begin /k:"murgocimark_net.core" /o:"murgocimark" /d:sonar.host.url="https://sonarcloud.io" /d:sonar.login="${{ secrets.SONAR_TOKEN }}"

      - name: Restore dependencies
        run: dotnet restore InvoiceManager/InvoiceManager.sln

      - name: Build
        run: dotnet build InvoiceManager/InvoiceManager.sln --no-restore --configuration Release

      - name: Run tests with coverage
        run: dotnet test InvoiceManager/InvoiceManager.sln --collect:"XPlat Code Coverage" --logger:trx
      
      - name: Convert coverage to Sonar format
        uses: danielpalme/ReportGenerator-GitHub-Action@5.1.23
        with:
          reports: '**/coverage.cobertura.xml'
          targetdir: 'coverage-report'
          reporttypes: 'Cobertura'

      - name: End SonarCloud analysis
        run: dotnet sonarscanner end /d:sonar.login="${{ secrets.SONAR_TOKEN }}"
